name: Callable Workflow

on: 
  workflow_call:
    inputs:
      name: 
        description: 'Name for greeting'
        required: true
        type: 'string'
    outputs:
      greetingMessage: 
        description: 'Generated greeting message'
        value: ${{ jobs.greet.outputs.message }}

jobs:
  greet:
    runs-on: ubuntu-latest
    outputs:
      message: ${{ steps.greeting.outputs.message }}
    steps:
    - id: greeting
      run: echo "::set-output name=message::Hello, ${{ inputs.name }}"
