name: Calling a reusable workflow
on:
 workflow_dispatch:
jobs:
  job1:
    uses: ./.github/workflows/Callable.yaml
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - run: echo ${{ needs.job1.output.firsword }}
