name: Grouping log line

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  bash-example:
    runs-on: ubuntu-latest
    steps:
      - name: Mask variable
        run: |
          echo "::add-mask::${{ vars.MY_NAME }}"
          echo "Masked value is set."

