name: Grouping log line

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  bash-example:
    runs-on: ubuntu-latest
    steps:
      - name: Group of log lines
        run: echo "::notice file=temp.js, line=1, col=3, endColumn=7::Missing weekend"
