name: Masking Secret Example

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  bash-example:
    runs-on: ubuntu-latest
    steps:
      - name: Mask secret
        run: echo "MY_ENV_VAR=Tanwar" >> $GITHUB_ENV
      - name : Assessing environment variable value
        run: echo "$MY_ENV_VAR"


       

