name: Grouping log line

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  bash-example:
    runs-on: ubuntu-latest
    steps:
      - name: Group of log lines
        run: echo echo "::warning file=app.js,line=1,col=5,endColumn=7::Missing semicolon"
