name: Masking Secret Example

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  bash-example:
    runs-on: ubuntu-latest
    steps:
      - name: Mask secret
        run: |
             echo "MY_ENV_VAR=Sapna Tanwar" >> $GITHUB_ENV
             echo "${{ env.MY_ENV_VAR }}"


       

