name: Callable Workflow

on: 
  workflow_call:
    inputs:
      name: 
        description: 'Name for greeting'
        required: true
        type: 'string'
    outputs:
      greetingMessage: 
        description: 'Generated greeting message'
        value: ${{ steps.greeting.outputs.message }}

jobs:
  greet:
    runs-on: ubuntu-latest
    outputs:
      greetingMessage: ${{ steps.greeting.outputs.message }}
    steps:
      - id: greeting
        run: |
          echo "message=Hello, ${{ inputs.name }}" >> $GITHUB_ENV
          echo "::set-output name=message::Hello, ${{ inputs.name }}"
