name: Use Python 3.11

on: [push]

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Cache Python installation
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-python-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-python-

      - name: Check Python version
        run: python --version

  job_2:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - name: Cache Python installation
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-python-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-python-

      - name: Check Python version
        run: python --version
