name: CI

on: [push]
   

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      python-version: ${{ steps.set_python.outputs.python-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        id: set_python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 

  build:
    runs-on: ubuntu-latest
    needs: setup  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
         python3 --version

     
