name: Install and Use Python

on: [push]

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Check Python version
        run: python3 --version

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "No requirements.txt found. Skipping dependency installation."
          fi

      - name: Save Python environment
        run: pip freeze > requirements.txt

      - name: Upload Python environment
        uses: actions/upload-artifact@v3
        with:
          name: python-env
          path: requirements.txt

  job_2:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - name: Download Python environment
        uses: actions/download-artifact@v3
        with:
          name: python-env

      - name: Check Python version
        run: python3 --version

      - name: Install dependencies from artifact
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "No requirements.txt found. Cannot install dependencies."
            exit 1
          fi
