name: Data sharing between jobs
on: [push]
jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          expr 3+7 > result.txt
      - name: uploading result to artifact
        uses: actions/upload-artifact@v3
        with:
          name: result
  
