name: Python Workflow

on: [push]

jobs:
  install-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create directories for Python installation
        run: |
          sudo mkdir -p /usr/local/python
          sudo chmod -R 755 /usr/local/python
          sudo chown -R $(whoami):$(whoami) /usr/local/python

      - name: Download Python 3.11
        run: |
          wget https://www.python.org/ftp/python/3.11.0/Python-3.11.0.tgz
          tar -xzf Python-3.11.0.tgz
          cd Python-3.11.0
          ./configure --enable-optimizations --prefix=/usr/local/python
          make altinstall
          cd ..
          rm -rf Python-3.11.0 Python-3.11.0.tgz

      - name: Check Python version
        run: |
          /usr/local/python/bin/python3.11 --version
          
      - name: Checking the location of python
        run: whereis python3
          
      - name: Upload Python installation as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: python-installation
          path: /usr/local/python
          
     

  use-python:
    runs-on: ubuntu-latest
    needs: install-python
    steps:
      - name: Download Python installation artifact
        uses: actions/download-artifact@v3
        with:
          name: python-installation
      - name: Checking the location of python
        run: whereis python3

      - name: Add Python to PATH
        run: echo "/usr/local/python/bin" >> $GITHUB_PATH
        

      - name: Check Python version
        run: |
          # Directly reference the installed Python executable
          /usr/local/python/bin/python3.11 --version
        
