name: CI

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        id: set_python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 
      - name: Install dependencies
        run: |
          python --version  

  build:
    runs-on: ubuntu-latest
    needs: setup  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python --version  
        

  
