name: Installing Python
on: [push]
jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Checking the version of python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Checking the version of Python
        run: python --version

        
            
