name: Python Workflow

on: [push]

jobs:
  install-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Download and install Python 3.11
        run: |
          wget https://www.python.org/ftp/python/3.11.0/Python-3.11.0.tgz
          tar -xzf Python-3.11.0.tgz
          cd Python-3.11.0
          ./configure --prefix=$HOME/python3.11 --enable-optimizations
          make
          make install
          cd ..
          rm -rf Python-3.11.0 Python-3.11.0.tgz

      - name: Add Python to PATH
        run: echo "$HOME/python3.11/bin" >> $GITHUB_PATH

      - name: Check the location of installed Python
        run: |
          python3.11 --version
          which python3.11

      - name: Upload Python executable
        uses: actions/upload-artifact@v3
        with:
          name: python3.11
          path: $HOME/python3.11/bin/python3.11  # Adjust path if necessary

  check-python:
    runs-on: ubuntu-latest
    needs: install-python
    steps:
      - name: Download Python artifact
        uses: actions/download-artifact@v3
        with:
          name: python3.11

      - name: Check Python version
        run: |
          # Make the downloaded Python executable accessible
          chmod +x ./python3.11
          ./python3.11 --version
          which ./python3.11
