name: Python Workflow

on: [push]

jobs:
  install-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Download and install Python 3.11
        run: |
          wget https://www.python.org/ftp/python/3.11.0/Python-3.11.0.tgz
          tar -xzf Python-3.11.0.tgz
          cd Python-3.11.0
          ./configure --enable-optimizations
          make altinstall
          cd ..
          rm -rf Python-3.11.0 Python-3.11.0.tgz

      - name: Check the location of installed Python
        run: |
          whereis python3.11


