name: Python Workflow

on: [push]

jobs:
  install-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download Python 3.11
        run: |
          wget https://www.python.org/ftp/python/3.11.0/Python-3.11.0.tgz
          tar -xzf Python-3.11.0.tgz
          cd Python-3.11.0
          ./configure --enable-optimizations --prefix=/usr/local/python
          make altinstall
          cd ..
          rm -rf Python-3.11.0 Python-3.11.0.tgz
      - name: Checking the local of installed python
        run: |
          sudo chmod -R 755 /usr/local/bin
          whereis python3.11
      - name: Check Python version
        run: |
          /usr/local/bin/python3.11 --version
 
